/**
 * Drive a monochrome SSD1306 OLED display (128x64 or 128x32) over I2C.
 *
 * Pure TypeScript on top of the `i2c` bus, so it needs no firmware change. Drawing
 * functions write to an in-memory framebuffer; call `show()` to push it to the panel
 * (or use `showString`, which pushes for you).
 */
//% color="#3949AB" weight=97 icon="" block="OLED"
namespace oled {
    // 5x7 font for printable ASCII 0x20..0x7E, 5 bytes per glyph (column-major, bit0=top).
    // Generated by tools/gen-oled-font.js (run with --render to eye-check the glyphs).
    const FONT = hex`000000000000005f00000007000700147f147f14242a7f2a12231308646236495522500005030000001c2241000041221c0014083e081408083e080800503000000808080808006060000020100804023e5149453e00427f400042615149462141454b311814127f1027454545393c4a49493001710905033649494936064949291e003636000000563600000814224100141414141400412214080201510906324979413e7e1111117e7f494949363e414141227f4141221c7f494949417f090909013e4149497a7f0808087f00417f41002040413f017f081422417f404040407f020c027f7f0408107f3e4141413e7f090909063e4151215e7f09192946464949493101017f01013f4040403f1f2040201f3f4038403f631408146307087008076151494543007f41410002040810200041417f0004020102044040404040000102040020545454787f484444383844444420384444487f3854545418087e0901020c5252523e7f0804047800447d40002040443d007f1028440000417f40007c041804787c0804047838444444387c14141408081414187c7c080404084854545420043f4440203c4040207c1c2040201c3c4030403c44281028440c5050503c4464544c44000836410000007f000000413608000804081008`;
    const FONT_FIRST = 0x20;
    const FONT_W = 5;

    let _addr = 0x3c;
    let _w = 128;
    let _h = 64;
    let _pages = 8;
    let _buf: Buffer = null;  // framebuffer, _pages*_w bytes (each byte = 8 vertical px)
    let _line: Buffer = null; // reusable [0x40, ...one page] I2C data transfer
    let _inited = false;

    function cmd(c: number): void {
        const b = control.createBuffer(2);
        b[0] = 0x00; // control byte: a command follows
        b[1] = c & 0xff;
        i2c.writeBuffer(_addr, b);
    }

    /**
     * Initialize the OLED. Call once before drawing. If you use non-default I2C pins,
     * call `i2c.init(sda, scl)` first.
     * @param width display width in pixels, eg: 128
     * @param height display height in pixels, eg: 64
     * @param address 7-bit I2C address, usually 60 (0x3C), eg: 60
     */
    //% blockId=oled_init block="OLED init width %width|height %height|address %address"
    //% width.defl=128 height.defl=64 address.defl=60 weight=100
    export function init(width: number = 128, height: number = 64, address: number = 0x3c): void {
        _w = width;
        _h = height;
        _addr = address;
        _pages = _h >> 3;
        _buf = control.createBuffer(_pages * _w);
        _line = control.createBuffer(_w + 1);
        _line[0] = 0x40; // control byte: pixel data follows

        const comPins = _h == 32 ? 0x02 : 0x12;
        cmd(0xae);              // display off
        cmd(0xd5); cmd(0x80);  // clock divide
        cmd(0xa8); cmd(_h - 1); // multiplex ratio
        cmd(0xd3); cmd(0x00);  // display offset
        cmd(0x40);             // start line 0
        cmd(0x8d); cmd(0x14);  // charge pump on
        cmd(0x20); cmd(0x00);  // horizontal addressing mode
        cmd(0xa1);             // segment remap
        cmd(0xc8);             // COM scan direction
        cmd(0xda); cmd(comPins);
        cmd(0x81); cmd(0xcf);  // contrast
        cmd(0xd9); cmd(0xf1);  // pre-charge
        cmd(0xdb); cmd(0x40);  // VCOMH
        cmd(0xa4);             // resume to RAM content
        cmd(0xa6);             // normal (not inverted)
        cmd(0xaf);             // display on
        _inited = true;
        clear();
        show();
    }

    function ensure(): void {
        if (!_inited) init();
    }

    /**
     * Clear the screen buffer (call `show()` to update the display).
     */
    //% blockId=oled_clear block="OLED clear" weight=86
    export function clear(): void {
        ensure();
        _buf.fill(0);
    }

    /**
     * Send the current buffer to the display.
     */
    //% blockId=oled_show block="OLED show" weight=84
    export function show(): void {
        ensure();
        cmd(0x21); cmd(0); cmd(_w - 1);      // column address range
        cmd(0x22); cmd(0); cmd(_pages - 1);  // page address range
        for (let p = 0; p < _pages; p++) {
            const base = p * _w;
            for (let x = 0; x < _w; x++) _line[x + 1] = _buf[base + x];
            i2c.writeBuffer(_addr, _line);
        }
    }

    /**
     * Set or clear a single pixel in the buffer (call `show()` to update).
     * @param x column, 0 at left
     * @param y row, 0 at top
     * @param on true to light the pixel, false to clear it
     */
    //% blockId=oled_set_pixel block="OLED set pixel x %x|y %y|on %on"
    //% on.shadow=toggleOnOff on.defl=true weight=70
    export function setPixel(x: number, y: number, on: boolean = true): void {
        ensure();
        if (x < 0 || x >= _w || y < 0 || y >= _h) return;
        const idx = (y >> 3) * _w + x;
        const bit = 1 << (y & 7);
        if (on) _buf[idx] = _buf[idx] | bit;
        else _buf[idx] = _buf[idx] & (~bit & 0xff);
    }

    function drawChar(x: number, y: number, code: number): void {
        if (code < FONT_FIRST || code > 0x7e) code = 0x20;
        const o = (code - FONT_FIRST) * FONT_W;
        for (let col = 0; col < FONT_W; col++) {
            const bits = FONT[o + col];
            for (let row = 0; row < 7; row++)
                if ((bits >> row) & 1) setPixel(x + col, y + row, true);
        }
    }

    /**
     * Draw text into the buffer at a pixel position (6 px per character).
     * Call `show()` to update the display.
     * @param text the text to draw
     * @param x left pixel position
     * @param y top pixel position
     */
    //% blockId=oled_show_string_at block="OLED draw %text|at x %x|y %y" weight=78
    export function showStringAt(text: string, x: number, y: number): void {
        ensure();
        let cx = x;
        for (let i = 0; i < text.length; i++) {
            drawChar(cx, y, text.charCodeAt(i));
            cx += FONT_W + 1;
        }
    }

    /**
     * Show text on a text line (0-based, 8 px tall), clearing that line first, and
     * update the display.
     * @param text the text to show
     * @param line the text row, eg: 0
     */
    //% blockId=oled_show_string block="OLED show %text|on line %line"
    //% line.defl=0 weight=82
    export function showString(text: string, line: number = 0): void {
        ensure();
        const y0 = line * 8;
        // clear the 8px-tall band for this line
        for (let y = y0; y < y0 + 8 && y < _h; y++)
            for (let x = 0; x < _w; x++) setPixel(x, y, false);
        showStringAt(text, 0, y0);
        show();
    }

    /**
     * Show a number on a text line.
     * @param value the number to show
     * @param line the text row, eg: 0
     */
    //% blockId=oled_show_number block="OLED show number %value|on line %line"
    //% line.defl=0 weight=81
    export function showNumber(value: number, line: number = 0): void {
        showString("" + value, line);
    }

    /**
     * Draw a filled rectangle into the buffer (call `show()` to update).
     */
    //% blockId=oled_fill_rect block="OLED fill rect x %x|y %y|width %w|height %h|on %on"
    //% on.shadow=toggleOnOff on.defl=true weight=60
    export function fillRect(x: number, y: number, w: number, h: number, on: boolean = true): void {
        ensure();
        for (let yy = y; yy < y + h; yy++)
            for (let xx = x; xx < x + w; xx++) setPixel(xx, yy, on);
    }

    /**
     * Invert the whole display (white-on-black vs black-on-white). Applies immediately.
     * @param on true to invert
     */
    //% blockId=oled_invert block="OLED invert %on"
    //% on.shadow=toggleOnOff weight=40
    export function invert(on: boolean = true): void {
        ensure();
        cmd(on ? 0xa7 : 0xa6);
    }
}
